# Préparation du df

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import statsmodels.api as sm
import seaborn as sns

pd.set_option('display.max_columns', None)
df = pd.read_csv(filepath_or_buffer = './data/ZonAnn.Ts+dSST.csv', sep = ',', header = 0, low_memory=False)
# df = pd.read_csv(filepath_or_buffer = './data/owid-co2-data.csv', sep = ',', header = 0, low_memory=False)

In [8]:
df.head()

,Year,Glob,NHem,SHem,24N-90N,24S-24N,90S-24S,64N-90N,44N-64N,24N-44N,EQU-24N,24S-EQU,44S-24S,64S-44S,90S-64S
0,1880,-0.18,-0.30,-0.05,-0.39,-0.14,-0.02,-0.80,-0.52,-0.29,-0.17,-0.11,-0.05,0.05,0.69
1,1881,-0.09,-0.18,0.00,-0.35,0.09,-0.07,-0.83,-0.46,-0.20,0.08,0.10,-0.06,-0.07,0.62
2,1882,-0.11,-0.22,-0.01,-0.31,-0.06,0.01,-1.33,-0.28,-0.15,-0.07,-0.05,0.01,0.04,0.65
3,1883,-0.17,-0.28,-0.07,-0.33,-0.18,-0.01,-0.12,-0.55,-0.25,-0.20,-0.16,-0.04,0.07,0.52
4,1884,-0.28,-0.43,-0.15,-0.60,-0.16,-0.14,-1.25,-0.64,-0.46,-0.14,-0.17,-0.20,-0.02,0.67

In [10]:
df.sort_values(by=['Year'], ascending=False).head()

,Year,Glob,NHem,SHem,24N-90N,24S-24N,90S-24S,64N-90N,44N-64N,24N-44N,EQU-24N,24S-EQU,44S-24S,64S-44S,90S-64S
144,2024,1.28,1.65,0.91,1.95,1.18,0.74,2.90,1.95,1.65,1.21,1.15,0.88,0.54,0.67
143,2023,1.17,1.49,0.85,1.78,1.06,0.72,2.57,1.87,1.46,1.08,1.03,0.91,0.46,0.64
142,2022,0.89,1.16,0.62,1.52,0.56,0.71,2.35,1.50,1.27,0.62,0.49,0.79,0.40,1.07
141,2021,0.85,1.14,0.55,1.43,0.65,0.53,2.06,1.36,1.26,0.72,0.58,0.73,0.33,0.29
140,2020,1.00,1.34,0.67,1.66,0.84,0.57,2.86,1.81,1.18,0.87,0.81,0.59,0.39,0.84

In [11]:
df.describe()

,Year,Glob,NHem,SHem,24N-90N,24S-24N,90S-24S,64N-90N,44N-64N,24N-44N,EQU-24N,24S-EQU,44S-24S,64S-44S,90S-64S
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000
mean,1952.000000,0.072621,0.104483,0.042552,0.133310,0.075931,0.008207,0.285655,0.154483,0.058276,0.062759,0.088345,0.052345,-0.047931,-0.059517
std,42.001984,0.392078,0.475796,0.326168,0.568116,0.367812,0.320327,1.033433,0.620574,0.449170,0.374009,0.367036,0.342262,0.282287,0.762778
min,1880.000000,-0.490000,-0.590000,-0.480000,-0.650000,-0.650000,-0.480000,-1.720000,-0.800000,-0.630000,-0.710000,-0.590000,-0.440000,-0.550000,-2.590000
25%,1916.000000,-0.200000,-0.220000,-0.210000,-0.290000,-0.200000,-0.240000,-0.370000,-0.280000,-0.240000,-0.210000,-0.180000,-0.220000,-0.260000,-0.520000
50%,1952.000000,-0.030000,0.000000,-0.050000,0.030000,0.000000,-0.070000,0.100000,0.010000,-0.060000,-0.010000,0.000000,-0.060000,-0.080000,0.070000
75%,1988.000000,0.310000,0.260000,0.280000,0.380000,0.310000,0.270000,0.770000,0.470000,0.180000,0.280000,0.320000,0.290000,0.200000,0.480000
max,2024.000000,1.280000,1.650000,0.910000,1.950000,1.180000,0.740000,3.240000,1.950000,1.650000,1.210000,1.150000,0.910000,0.540000,1.320000

In [12]:
# Affichage nb lignes et colonnes
df.shape

(145, 15)

In [11]:
# Nombre de valeurs uniques dans Col1 : ..
df['Year'].unique()

array([1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890,
       1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901,
       1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912,
       1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923,
       1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934,
       1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945,
       1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956,
       1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967,
       1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978,
       1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989,
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [12]:
# Affichage des types de chaque colonne
df.dtypes

Year         int64
Glob       float64
NHem       float64
SHem       float64
24N-90N    float64
24S-24N    float64
90S-24S    float64
64N-90N    float64
44N-64N    float64
24N-44N    float64
EQU-24N    float64
24S-EQU    float64
44S-24S    float64
64S-44S    float64
90S-64S    float64
dtype: object

# Nettoyage des données

In [10]:
# Calcul du nombre de doublons
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Col1'] = df['Col1'].fillna(0)
df['Col2'] = df['Col2'].fillna(0)
# etc.

print('Col1', df['Col1'].isna().sum(axis = 0))
print('Col2', df['Col2'].isna().sum(axis = 0))

In [ ]:
df.head()

In [ ]:
# Remplacement des données type string dans la colonne 'Col1' par float
df['Col1'] = df['Col1'].replace(to_replace = ["ND", "-"], value = 0)
df['Col1'] = df['Col1'].astype(float)

# Affichage du df

In [ ]:
# Affichage du df selon ordre ascendant ou descendant d'une colonne
df.sort_values(by=['ColDate'], ascending=False).head(1)

In [ ]:
# Calcul et affichage de la somme d'une colonne Col2
print('Col2', df['Col2'].sum())

# Création nouveau df_new

In [ ]:
df_new = df
df_new.head(1)

In [ ]:
# Suppression des colonnes inutiles
df_new.drop(['Col99', 'Col98'], axis=1, inplace=True)

In [ ]:
df_new.head(1)

In [ ]:
# Retraitement d'une colonne de date
df_new['Date'].dtypes
df_new['Date'] = pd.to_datetime(df_new['Date'])

In [ ]:
# Création d'une colonne 'Année' qui récupère l'année pour chaque ligne 
df_new['Année'] = df_new['Date'].dt.year

In [ ]:
# Création d'une colonne 'ColTotal' qui calcule la somme de deux colonnes
df_new['ColTotal'] = df_new['Col1'] + df_new['Col2']

In [ ]:
# Création d'une colonne 'ColDiff' qui calcule le différentiel entre deux colonnes
df_new['ColDiff'] = df_new['Col3'] - df_new['Col4']

In [ ]:
# Modification de la place de la colonne ColMove à l'index 2
ColMove = df_new.pop('ColMove')
df_new.insert(2, ColMove.name, ColMove)

In [ ]:
df_new.head(10)

# Création des KPIs

In [ ]:
print('Total de la colonne Col1', f"{df_new['Col1'].sum():,}")

In [ ]:
# Affichage des principaux KPI pour chaque critère
titreKpiGroupByCriteria = 'KPI par critère'
kpiGroupByCriteria = df_new.groupby('ColCriteria').agg({'Col1': 'sum', 'Col2': 'sum', 'Col3': 'sum', 'ColDiff': 'sum', }).reset_index()
print(titreKpiGroupByCriteria)
kpiGroupByCriteria.sort_values(by=['Col1'], ascending=False)

In [ ]:
# Barplot par région sur 2013-2024
kpiGroupByCriteria = kpiGroupByCriteria.sort_values(by=['Col1'], ascending=False)
fig, (ax) = plt.subplots(figsize=(10, 5))

ylabel = 'Col1 value (échelle : 1 = 1 000 TW)'
bar_labels = ['red', 'blue', 'green', 'orange', 'purple', 'cyan', 'brown', 'pink', 'gray', 'olive', 'green', 'blue']
bar_colors = ['tab:red', 'tab:blue', 'tab:green', 'tab:orange', 'tab:purple', 'tab:cyan', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:green', 'tab:blue']

bar_container = ax.bar(kpiGroupByCriteria['ColCriteria'], kpiGroupByCriteria['Col1'])

ax.bar(kpiGroupByCriteria['ColCriteria'], kpiGroupByCriteria['Col1'], label=bar_labels, color=bar_colors)
ax.bar_label(bar_container, fmt='{:,.0f}', rotation='vertical', fontsize=8, label_type='center')
ax.set_ylabel(ylabel)

plt.xticks(rotation=45, ha='right')

In [ ]:
kpiGroupByCriteria['Col2'].sum()

In [ ]:
# Affichage des principaux KPI pour chaque année
kpiGroupByYear = df_new.groupby('Année').agg({'Col1': 'sum', 'Col1': 'sum', 'ColDiff': 'sum', 'Col2': 'sum'})
kpiGroupByYear.sort_values(by=['Année'], ascending=False)

In [ ]:
sns.lineplot(data=kpiGroupByYear['Col1'])

# Analyse par ColCriteria

In [ ]:
# Affichage des volumes de production par filière pour chaque région
prodGroupByCriteria = df_new.groupby('ColCriteria').agg({'Col1': 'sum', 'Col2': 'sum'}).reset_index()
prodGroupByCriteria.sort_values(by=['Col1'], ascending=False)

In [ ]:
# Création d'un df indiquant les % de chaque critère dans la production pour chaque filière
prodGroupByCriteriaPercentage = prodGroupByCriteria

# Création des colonnes qui indique le ratio 'Filière (MW)' / 'Production (MW)'
prodGroupByCriteriaPercentage['Col99 (%)'] = prodGroupByCriteria['Col1'] / prodGroupByCriteria['Coltotal'].sum()

In [ ]:
prodGroupByCriteriaPercentage.sort_values(by=['Col3'], ascending=False)

# Analyse par Criteria2

In [ ]:
labels = prodGroupByCriteriaPercentage['Criteria']
sizes = prodGroupByCriteriaPercentage['ColCriteria2']

explode = prodGroupByCriteriaPercentage['ColCriteria2'].apply(lambda x:x > 100)
explode = explode.apply(lambda x:0.2 if x == True else 0)
print("Part respective de chaque Criteria dans la ColCriteria2")
plt.title("")
plt.pie(sizes, explode=explode,autopct='%1.2f%%',shadow=True, radius=2)
plt.legend(labels, loc="center")
plt.show()

In [ ]:
import squarify

# Sample data
values = prodGroupByCriteriaPercentage['ColCriteria3']
perc = [str('{:5.2f}'.format(i/prodGroupByCriteriaPercentage['ColCriteria3'].sum()*100)) + "%" for i in prodGroupByCriteriaPercentage['ColCriteria3']]
labels = [f'{crit1}\n{rate}' for crit1, rate in zip(prodGroupByCriteriaPercentage['Criteria'], perc)]

# Treemap
colors = ['#91DCEA', "#C02E29", '#5FBB68', "#DDF508", "#F929D6", "#DDD9D7", "#464FC4", "#08B42D", "#F5D20F", "#2E4E6D", "#E0B470", "#7BF707"]
squarify.plot(sizes = values, label = labels, pad = 0.3, text_kwargs = {'fontsize': 6, 'color': 'black'}, color = colors, alpha = 0.7)

# Remove the axis:
plt.axis("off")

plt.show()

# Analyse par année

## Affichage du lineplot

In [ ]:
# Affichage des volumes de production par filière pour chaque année
prodGroupByYearLine = df_new.groupby('Année').agg({'Col1': 'sum', 'Col2': 'sum'})
prodGroupByYearLine.sort_values(by=['Année'], ascending=True)

In [ ]:
# Création d'un df stacked indiquant les parts (en %) de chaque filière dans la production pour chaque région
prodGroupByYearPercentageLine = prodGroupByYearLine

# Création des colonnes indiquant le ratio 'Filière (MW)' / 'Production (MW)'
prodGroupByYearPercentageLine['Col1'] = prodGroupByYearLine['Col1'] / prodGroupByYearLine['ColTotal']

In [ ]:
sns.lineplot(data=prodGroupByYearPercentageLine)

## Affichage du stackplot

In [ ]:
# Affichage des volumes de production par filière pour chaque année
prodGroupByYearStack = df_new.groupby('Année').agg({'Col1': 'sum', 'Col2': 'sum'}).reset_index()
prodGroupByYearStack.sort_values(by=['Année'], ascending=True)

In [ ]:
# Création d'un df stacked indiquant les parts (en %) de chaque filière dans la production pour chaque région
prodGroupByYearPercentage = prodGroupByYearStack

# Création des colonnes indiquant le ratio 'Filière (MW)' / 'Production (MW)'
prodGroupByYearPercentage['Col1 (%)'] = prodGroupByYearStack['Col1 (vol)'] / prodGroupByYearStack['ColTotal (vol)']

# Suppression des colonnes inutiles

In [ ]:
prodGroupByYearPercentage.sort_values(by=['Année'], ascending=False)

In [ ]:
x = prodGroupByYearPercentage['Année']
y1 = prodGroupByYearPercentage['Col1 (%)']
y2 = prodGroupByYearPercentage['Col2 (%)']
y3 = prodGroupByYearPercentage['Col3 (%)']


plt.bar(x, y1, color='black')
plt.bar(x, y2, bottom=y1, color='yellow')
plt.bar(x, y3, bottom=y1+y2, color='green')
plt.xlabel("Année")
plt.ylabel("% production totale")
plt.legend(["Col1 (%)", "Col2 (%)", "Col3 (%)"])
plt.title("Part de chaque col dans le total")
plt.show()

In [ ]:
prodGroupByYearPercentage.plot(x='Année', kind='bar', stacked=True,
        title='Part de chaque col dans le total')
plt.show()

# Boxplot KPI * Région * Période 10 ans

In [ ]:
# Traçage d'un boxplot à partir des valeurs de la colonne "Consommation (MW)"
titre1 = 'Répartition du KPI par Col1 sur la période ...'
print(titre1)
sns.boxplot(x=kpiGroupByCriteria['Col1'], color=".8")

# Qqplot

In [ ]:
# Boucle qui permet d'afficher les Q-Q plots: 
for column in kpiGroupByCriteria.columns:
    print(column)
    sm.qqplot(kpiGroupByCriteria[column], line='45', fit = True)